### ISSUE TITLE
"inline" metadata load is broken as of version 2.3.0

### ISSUE THREAD

**Issue by tombriles** [IdentityPython/pysaml2#203] opened 2015-04-16 15:55 UTC
Here is a sample stack trace:

```
  File "/home/devbuild/working_dir/flask_pysaml2/flask_pysaml2.py", line 207, in __init__
    self._config = SPConfig().load(config)
  File "/opt/kavi/service/web/ve/lib/python2.7/site-packages/pysaml2-2.4.0-py2.7.egg/saml2/config.py", line 353, in load
    self.load_complex(cnf, metadata_construction=metadata_construction)
  File "/opt/kavi/service/web/ve/lib/python2.7/site-packages/pysaml2-2.4.0-py2.7.egg/saml2/config.py", line 293, in load_complex
    self.load_metadata(cnf["metadata"]))
  File "/opt/kavi/service/web/ve/lib/python2.7/site-packages/pysaml2-2.4.0-py2.7.egg/saml2/config.py", line 398, in load_metadata
    mds.imp(metadata_conf)
  File "/opt/kavi/service/web/ve/lib/python2.7/site-packages/pysaml2-2.4.0-py2.7.egg/saml2/mdstore.py", line 814, in imp
    self.load(key, val)
  File "/opt/kavi/service/web/ve/lib/python2.7/site-packages/pysaml2-2.4.0-py2.7.egg/saml2/mdstore.py", line 800, in load
    _md.load()
  File "/opt/kavi/service/web/ve/lib/python2.7/site-packages/pysaml2-2.4.0-py2.7.egg/saml2/mdstore.py", line 186, in load
    self.parse(self.metadata)
  File "/opt/kavi/service/web/ve/lib/python2.7/site-packages/pysaml2-2.4.0-py2.7.egg/saml2/mdstore.py", line 180, in parse
    raise NotImplementedError
NotImplementedError: 
```

This patch (for master) seems to fix it:

```
diff --git a/src/saml2/mdstore.py b/src/saml2/mdstore.py
index 36344cf..aa96e6b 100644
--- a/src/saml2/mdstore.py
+++ b/src/saml2/mdstore.py
@@ -777,7 +777,7 @@ class MetadataStore(object):
         elif typ == "inline":
             self.ii += 1
             key = self.ii
-            _md = MetaData(self.onts, self.attrc, args[0], **kwargs)
+            _md = InMemoryMetaData(self.onts, self.attrc, args[0], **kwargs)
         elif typ == "remote":
             key = kwargs["url"]
             _args = {}
```

**Comment by dcoleman17** [comment] 2015-04-21 23:16
To Reproduce: 
```
from saml2.config import Config
idp_data = #string representation of XML idp definition

saml_config = Config()

config_dict = {
    "metadata": { "inline": idp_metadata }
}
cfg = saml_config.load(config_dict) 
```
The traceback is
```
Traceback (most recent call last):
  File "./st.py", line 201, in <module>
    cfg = saml_config.load(old_config_dict)
  File "/home/vagrant/dogweb/python/lib/python2.7/site-packages/saml2/config.py", line 353, in load
    self.load_complex(cnf, metadata_construction=metadata_construction)
  File "/home/vagrant/dogweb/python/lib/python2.7/site-packages/saml2/config.py", line 293, in load_complex
    self.load_metadata(cnf["metadata"]))
  File "/home/vagrant/dogweb/python/lib/python2.7/site-packages/saml2/config.py", line 398, in load_metadata
    mds.imp(metadata_conf)
  File "/home/vagrant/dogweb/python/lib/python2.7/site-packages/saml2/mdstore.py", line 814, in imp
    self.load(key, val)
  File "/home/vagrant/dogweb/python/lib/python2.7/site-packages/saml2/mdstore.py", line 800, in load
    _md.load()
  File "/home/vagrant/dogweb/python/lib/python2.7/site-packages/saml2/mdstore.py", line 186, in load
    self.parse(self.metadata)
  File "/home/vagrant/dogweb/python/lib/python2.7/site-packages/saml2/mdstore.py", line 180, in parse
    raise NotImplementedError
NotImplementedError
```

Using a different format to specify the metadata does work:

```
from saml2.config import Config
idp_data = #string representation of XML idp definition

saml_config = Config()

config_dict = {
    "metadata": [{
        "class": "saml2.mdstore.InMemoryMetaData",
        "metadata": [(idp_metadata, )]
    }]
}

cfg = saml_config.load(config_dict) 
```

**Comment by mhahn** [comment] 2015-09-02 05:03
getting this as well

**Comment by claytondaley** [comment] 2018-10-29 22:48
Works for me IF I wrap the value for `inline` in a list e.g.

```
config_dict = {
    "metadata": { "inline": [idp_metadata] }
}
```

I suggest closing the issue.

**Closed** 2020-09-05 19:24 UTC
