### ISSUE TITLE
AuthnResponse._verify() returns None which throws uncaught error in entity.py

### ISSUE THREAD

**Issue by daxaxelrod** [IdentityPython/pysaml2#611] opened 2019-04-30 15:26 UTC
https://github.com/IdentityPython/pysaml2/blob/d3aa78eeb7d37c12688f783cb4db1c7263a14ad6/src/saml2/entity.py#L1202

https://github.com/IdentityPython/pysaml2/blob/845fc7d40c3f81b79a95bbbea7a82953a54572c4/src/saml2/response.py#L408

Facing this issue myself where my destination isnt correct. I can fix that but line 1202 and the subsequent finally on line 1212 in enitity.py expect response to not be none as it tries to set require_signature on a NoneType.

Maybe we can throw some more descriptive signature errors in _verify() that are then caught by line 1203?

**Comment by pgrzesik** [comment] 2019-05-07 12:26
+1, stumbled upon the exact same issue with mismatching destination

**Comment by sheilatron** [comment] 2019-05-20 16:58
This looks like a duplicate of #598 
https://github.com/IdentityPython/pysaml2/issues/598

**Closed** 2020-09-06 01:15 UTC
