### ISSUE TITLE
metadata maker is generating empty URI in ServiceName element

### ISSUE THREAD

**Issue by rhoerbe** [IdentityPython/pysaml2#345] opened 2016-06-24 09:23 UTC
Pysaml2 is generating an <--ns0:ServiceName xml:lang="en"/> element for the AttributeConsumingService, which is XML schema valid, but not allowed according to SAML core:

1.3.2 URI Values
.. 
Unless otherwise indicated in this specification, all URI reference values used within SAML-defined elements or attributes MUST consist of at least one non-whitespace character ..

**Comment by rhoerbe** [comment] 2016-06-24 09:33
Ah, my bad, this is not an localizedURIType, it is a localizedNameType. I got confused by the OpenSAML error message

**Comment by rhoerbe** [comment] 2016-06-24 17:59
jut learned that strings cannot be blank, like URIs:
SAML core 1.3.1 String Values:
... Unless otherwise noted in this specification or particular profiles, all strings in SAML messages MUST consist of at least one non-whitespace character

**Comment by peppelinux** [comment] 2020-09-05 23:39
Hi @rhoerbe, I can't reproduce this in my asset, I have a SP with a correct valued ACS.
Can give more information about how to reproduce this?

**Comment by rhoerbe** [comment] 2020-09-06 18:48
I passed on my SATOSA-related projects, so I have no dev env available in the time since. But if pysaml now is creating a proper string value, or no ServiceName at all, then the problem should be fixed.

**Comment by peppelinux** [comment] 2020-09-06 18:56
Thank you for ack. I close this for now because It looks good to me, if someone Will update this thread I'll open It again

👍

**Closed by peppelinux** 2020-09-06 18:56 UTC
Labels: bug, closing

**Comment by melanger** [comment] 2021-11-16 13:41
@peppelinux This was probably caused by a missing `name` under the `sp` key in config, such as in the example SATOSA SAML2 backend config. I created https://github.com/IdentityPython/SATOSA/pull/393 to address that.
